### ISSUE TITLE
is this EE/EET compatible

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Sampsca/Auroras-Shoes-and-Boots#2]
i can not find anything related to EE/EET support in the readme

**Comment by Sampsca** [comment]
No, this is not compatible with the EEs.  I planned on adding EE support a long time ago, but doing so requires a significant rewrite of the code, and it made sense to wait until the new version of Infinity Animations (IA) was released because of the significant role those animations play in this mod.  Sadly, the new EE-compatible version of IA took a bit longer to release than expected, then was delayed temporarily, and now temporarily has turned into years.  A while back she-who-must-not-be-named created an unauthorized version of this mod that added EE compatibility but dropped a significant portion of the content as well as backwards compatibility.  It's probably lurking around the darkweb somewhere if you want to try it, but please don't bring bug reports from that version here.
